name: Generate Contribution Snake Animation

on:
  schedule:
    - cron: "0 */12 * * *" # Run every 12 hours
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  generate:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - uses: actions/checkout@v4

      - name: Generate Contribution Grid Animation
        uses: Platane/snk@v3
        with:
          github_user_name: vibhortanwar
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark
        env:
          # Use your Personal Access Token to include private contributions
          GITHUB_TOKEN: ${{ secrets.PAT_PACMAN }}

      - name: Deploy SVGs to Output Branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: pacman-output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
